version: "3.8"
services:
  backend:
    build: ./backend
    image: k2b-backend
    ports:
      - "5018:5018"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    image: k2b-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      # If your frontend needs to know backend URL, set VITE_BACKEND_URL here
      - VITE_BACKEND_URL=http://localhost:5018
